file = open("output.txt",'w')
text = input("Enter text to write to the file: ")
file.write(text)
file.write('\n')
print("Data successfully written to output.txt")
print()
print()
file.close()

file1 = open("output.txt",'a')
add = input("Enter additional text to append: ")
file1.write(add)
print("Data successfully appended")
print()
print()
file1.close()

file2 = open("output.txt",'r')
getRead = file2.read()
print(getRead)
file.close()
